
"""
Pepforge PyMOL Structure Tool core
v1.3.0

Purpose
-------
Create a chemically connected 3D starting model for modified peptides and
export SDF/PDB/JSON files that can be loaded and inspected in PyMOL.

Fixed interpretation rule
-------------------------
STD AA      : A C D E F G H I K L M N P Q R S T V W Y
D-form      : dA, dK, dF, ... ; chirality-inverted canonical residue
Non-natural : Aib, Nle, Orn, Dab, Cit, Hyp, Cha, Nal, ... ; sequence monomer
Linker      : Ahx, PEG4, PEG8, AEEA, bAla, gAla ; spacer, not STD residue
Label       : Biotin, FITC, FAM, TAMRA, Cy5, NBD, DOTA ; modification/label, not peptide residue
Terminal    : Ac, Boc, NH2, OH ; terminal modifications
Side-chain  : K(FITC), K(Ahx-Biotin), C(NBD), Orn(Biotin), Dab(FITC)

Important limitation
--------------------
This is a PyMOL/visualization-grade connected 3D starting model generator.
Large labels use template-ready attachment metadata in v1.3.0. The default
geometry is still generated by RDKit from validated SMILES, but each linker/label/
non-natural token now has an attach-point manifest and template SDF placeholder
that can be replaced by curated SDF templates without changing the user syntax.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import re
import json
import csv

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, Descriptors, rdMolDescriptors
except Exception as exc:  # pragma: no cover
    Chem = None
    AllChem = None
    Descriptors = None
    rdMolDescriptors = None
    _RDKIT_IMPORT_ERROR = exc
else:
    _RDKIT_IMPORT_ERROR = None

VERSION = "1.3.0"

# -----------------------------------------------------------------------------
# Monomer/linker/label libraries
# -----------------------------------------------------------------------------
L_RESIDUE_UNITS: Dict[str, str] = {
    "G": "NCC(=O)",
    "A": "N[C@@H](C)C(=O)",
    "V": "N[C@@H](C(C)C)C(=O)",
    "L": "N[C@@H](CC(C)C)C(=O)",
    "I": "N[C@@H]([C@H](C)CC)C(=O)",
    "S": "N[C@@H](CO)C(=O)",
    "T": "N[C@@H]([C@H](O)C)C(=O)",
    "C": "N[C@@H](CS)C(=O)",
    "M": "N[C@@H](CCSC)C(=O)",
    "D": "N[C@@H](CC(=O)O)C(=O)",
    "E": "N[C@@H](CCC(=O)O)C(=O)",
    "N": "N[C@@H](CC(=O)N)C(=O)",
    "Q": "N[C@@H](CCC(=O)N)C(=O)",
    "K": "N[C@@H](CCCCN)C(=O)",
    "R": "N[C@@H](CCCNC(=N)N)C(=O)",
    "H": "N[C@@H](Cc1c[nH]cn1)C(=O)",
    "F": "N[C@@H](Cc1ccccc1)C(=O)",
    "Y": "N[C@@H](Cc1ccc(O)cc1)C(=O)",
    "W": "N[C@@H](Cc1c[nH]c2ccccc12)C(=O)",
    "P": "N1CCC[C@H]1C(=O)",
}
D_RESIDUE_UNITS: Dict[str, str] = {
    "G": "NCC(=O)",
    "A": "N[C@H](C)C(=O)",
    "V": "N[C@H](C(C)C)C(=O)",
    "L": "N[C@H](CC(C)C)C(=O)",
    "I": "N[C@H]([C@@H](C)CC)C(=O)",
    "S": "N[C@H](CO)C(=O)",
    "T": "N[C@H]([C@@H](O)C)C(=O)",
    "C": "N[C@H](CS)C(=O)",
    "M": "N[C@H](CCSC)C(=O)",
    "D": "N[C@H](CC(=O)O)C(=O)",
    "E": "N[C@H](CCC(=O)O)C(=O)",
    "N": "N[C@H](CC(=O)N)C(=O)",
    "Q": "N[C@H](CCC(=O)N)C(=O)",
    "K": "N[C@H](CCCCN)C(=O)",
    "R": "N[C@H](CCCNC(=N)N)C(=O)",
    "H": "N[C@H](Cc1c[nH]cn1)C(=O)",
    "F": "N[C@H](Cc1ccccc1)C(=O)",
    "Y": "N[C@H](Cc1ccc(O)cc1)C(=O)",
    "W": "N[C@H](Cc1c[nH]c2ccccc12)C(=O)",
    "P": "N1CCC[C@@H]1C(=O)",
}
NON_NATURAL_UNITS: Dict[str, str] = {
    "Aib": "NC(C)(C)C(=O)",
    "Nle": "N[C@@H](CCCC)C(=O)", "dNle": "N[C@H](CCCC)C(=O)",
    "Orn": "N[C@@H](CCCN)C(=O)", "dOrn": "N[C@H](CCCN)C(=O)",
    "Dab": "N[C@@H](CCN)C(=O)", "dDab": "N[C@H](CCN)C(=O)",
    "Cit": "N[C@@H](CCCNC(=O)N)C(=O)", "dCit": "N[C@H](CCCNC(=O)N)C(=O)",
    "Hyp": "N1C[C@H](O)C[C@H]1C(=O)", "dHyp": "N1C[C@@H](O)C[C@@H]1C(=O)",
    "Cha": "N[C@@H](CC1CCCCC1)C(=O)", "dCha": "N[C@H](CC1CCCCC1)C(=O)",
    "Nal": "N[C@@H](Cc1cccc2ccccc12)C(=O)", "dNal": "N[C@H](Cc1cccc2ccccc12)C(=O)",
}
LINKER_UNITS: Dict[str, str] = {
    "Ahx": "NCCCCCC(=O)",
    "bAla": "NCCC(=O)",
    "gAla": "NCCCC(=O)",
    "AEEA": "NCCOCCNC(=O)",
    "PEG4": "NCCOCCOCCOCCNC(=O)",
    "PEG8": "NCCOCCOCCOCCOCCOCCNC(=O)",
}
# Terminal labels are appended after a carbonyl, so they start with N when possible.
LABEL_UNITS: Dict[str, str] = {
    "Biotin": "NCCCCC1SCC2NC(=O)NC12",
    "FITC": "NCC(=O)c1ccc(N=C=S)cc1C(=O)",
    "FAM": "NCC(=O)c1ccc(O)cc1C(=O)",
    "TAMRA": "NCC(=O)c1ccc(N(C)C)cc1C(=O)",
    "NBD": "Nc1ccc([N+](=O)[O-])c2nonc12",
    "DOTA": "NCCN1CCN(CCN(CCN(CC1)CC(=O)O)CC(=O)O)CC(=O)O",
    "Cy5": "NCC=CC=CC=CN1C=CC=C1",
}
# Chemical groups are non-sequence modifications. They can be placed terminally
# or inside side-chain syntax, e.g. K(Pal), K(Chol), K(Ahx-Biotin).
# These are visualization-grade connected units for PyMOL inspection.
CHEMICAL_UNITS: Dict[str, str] = {
    # Internal/standalone chemical fragments retain an entering N for generic
    # visualization-linkage use. Terminal lipid caps are handled separately
    # below so Pal-dG-... is palmitoyl-NH-peptide, not amino-palmitoyl.
    "Pal": "NCCCCCCCCCCCCCCCC(=O)",        # generic palmitoyl-like display unit
    "Myr": "NCCCCCCCCCCCCCC(=O)",          # generic myristoyl-like display unit
    "Ste": "NCCCCCCCCCCCCCCCCCC(=O)",      # generic stearoyl-like display unit
    "Lau": "NCCCCCCCCCCCC(=O)",            # generic lauroyl-like display unit
    "Chol": "NCCOC(=O)CCCC(=O)OC1CCC2(C)C3CCC4(C)CC(O)CCC4C3CCC12C",
    "Gal": "Nc1cc(O)c(O)c(O)c1C(=O)",     # galloyl/gallic-acid-like display unit
    "Caf": "N/C=C/c1ccc(O)c(O)c1C(=O)",   # caffeoyl/caffeic-acid-like display unit
    "Nic": "Nc1ccncc1C(=O)",              # nicotinoyl-like display unit
    "Mal": "NCC(=O)C1=CC=CC=C1",          # simplified maleimide/aryl linker display
    "Dde": "NCC(=O)C=C(C)C(=O)C",
}

# v2.0.0 hotfix: N-terminal lipid tokens must be acyl caps.
# Example: Pal-dG-dH-dK-NH2 should become
# CH3-(CH2)14-C(=O)-NH-dG-dH-dK-C(=O)-NH2.
# The previous generic CHEMICAL_UNITS form started with N and could be
# visualized incorrectly as a strange free chemical fragment.
N_TERMINAL_ACYL_CHEM_CAPS: Dict[str, str] = {
    "Pal": "CCCCCCCCCCCCCCCC(=O)",          # palmitoyl, C16 acyl cap
    "Myr": "CCCCCCCCCCCCCC(=O)",            # myristoyl, C14 acyl cap
    "Ste": "CCCCCCCCCCCCCCCCCC(=O)",        # stearoyl, C18 acyl cap
    "Lau": "CCCCCCCCCCCC(=O)",              # lauroyl, C12 acyl cap
    "Gal": "O=C(c1cc(O)c(O)c(O)c1)",        # galloyl / gallic acid N-terminal cap
    "Caf": "O=C(/C=C/c1ccc(O)c(O)c1)",      # caffeoyl / caffeic acid N-terminal cap
    "Nic": "O=C(c1ccncc1)",                 # nicotinoyl / nicotinic acid N-terminal cap
}

# Tail fragments used when a lipid is attached through an already-written
# amide carbonyl, e.g. K(Pal) -> Lys-NH-C(=O)-(CH2)14-CH3.
SIDECHAIN_ACYL_TAILS: Dict[str, str] = {
    "Pal": "CCCCCCCCCCCCCCC",
    "Myr": "CCCCCCCCCCCCC",
    "Ste": "CCCCCCCCCCCCCCCCC",
    "Lau": "CCCCCCCCCCC",
    "Gal": "c1cc(O)c(O)c(O)c1",
    "Caf": "/C=C/c1ccc(O)c(O)c1",
    "Nic": "c1ccncc1",
}
N_TERMINAL_CAPS: Dict[str, str] = {"Ac": "CC(=O)", "Boc": "CC(C)(C)OC(=O)", "Fmoc": "O=C(OCC1c2ccccc2-c2ccccc21)"}
C_TERMINAL_CAPS = {"OH", "NH2"}
TAG_EXPANSIONS: Dict[str, str] = {
    "His6": "HHHHHH", "His8": "HHHHHHHH", "FLAG": "DYKDDDDK",
    "HA": "YPYDVPDYA", "Myc": "EQKLISEEDL", "Strep": "WSHPQFEK",
}
# User-facing aliases. STD is intentionally not changed: STD AA means the 20 canonical residues.
TOKEN_ALIASES: Dict[str, str] = {
    "amide": "NH2", "Amide": "NH2", "CtermNH2": "NH2",
    "acetyl": "Ac", "Acetyl": "Ac",
    "biotin": "Biotin", "fitc": "FITC", "fam": "FAM", "tamra": "TAMRA", "cy5": "Cy5",
    "6Ahx": "Ahx", "Acp": "Ahx",
    "pal": "Pal", "PAL": "Pal", "palmiticacid": "Pal", "Palmiticacid": "Pal", "PalmiticAcid": "Pal", "palmitoyl": "Pal", "Palmitoyl": "Pal",
    "myr": "Myr", "MYR": "Myr", "myristicacid": "Myr", "MyristicAcid": "Myr", "myristoyl": "Myr",
    "gal": "Gal", "GAL": "Gal", "gallicacid": "Gal", "GallicAcid": "Gal", "galloyl": "Gal",
    "caf": "Caf", "CAF": "Caf", "caffeicacid": "Caf", "CaffeicAcid": "Caf", "caffeoyl": "Caf",
    "nic": "Nic", "NIC": "Nic", "nicotinicacid": "Nic", "NicotinicAcid": "Nic", "nicotinoyl": "Nic",
    "stearoyl": "Ste",
    "cholesterol": "Chol", "Cholesterol": "Chol", "chol": "Chol",
}
STD_AA = set(L_RESIDUE_UNITS)
KNOWN_MULTI_TOKENS = sorted(
    set(N_TERMINAL_CAPS) | C_TERMINAL_CAPS | set(NON_NATURAL_UNITS) |
    set(LINKER_UNITS) | set(LABEL_UNITS) | set(CHEMICAL_UNITS) | set(TAG_EXPANSIONS) | set(TOKEN_ALIASES),
    key=len, reverse=True,
)
KIND_LABELS = {
    "n_terminal": "N-terminal modification",
    "c_terminal": "C-terminal modification",
    "std_aa": "STD L-amino acid",
    "d_std_aa": "STD D-amino acid",
    "non_natural_aa": "Non-natural amino acid",
    "linker": "Linker/spacer",
    "label": "Label/modification",
    "chemical": "Chemical modification",
    "tag_expansion": "Expanded affinity/epitope tag",
    "sidechain_label_aa": "Side-chain labeled amino acid",
    "c_terminal_atom": "C-terminal added atom",
}
SIDECHAIN_ACCEPTORS = {"K", "dK", "Orn", "dOrn", "Dab", "dDab", "C", "dC"}




def _infer_local_attach_points(smiles: Optional[str], category: str) -> Dict[str, Optional[int]]:
    """Infer 1-based heavy-atom ranks used as attach-site hints."""
    result: Dict[str, Optional[int]] = {"in_atom_1based": None, "out_atom_1based": None}
    if not smiles or Chem is None:
        return result
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return result
    for a in mol.GetAtoms():
        if a.GetAtomicNum() == 7:
            result["in_atom_1based"] = int(a.GetIdx()) + 1
            break
    carbonyls = []
    for a in mol.GetAtoms():
        if a.GetAtomicNum() != 6:
            continue
        for b in a.GetBonds():
            other = b.GetOtherAtom(a)
            if other.GetAtomicNum() == 8 and int(b.GetBondTypeAsDouble()) == 2:
                carbonyls.append(int(a.GetIdx()) + 1)
                break
    if category in {"std_aa", "d_std_aa", "sidechain_label_aa", "non_natural_aa", "linker", "chemical", "n_terminal"} and carbonyls:
        result["out_atom_1based"] = max(carbonyls)
    if category == "label":
        result["out_atom_1based"] = None
    return result

# v1.3 attachment-aware template registry. Current SDF files are RDKit-generated placeholders,
# but the manifest records how each token is meant to attach. A curated SDF can be
# substituted later if it preserves the same token name and attachment roles.
TEMPLATE_ATTACHMENT_RULES: Dict[str, Dict[str, Any]] = {
    "non_natural_aa": {
        "chain_in": "backbone_N",
        "chain_out": "backbone_carbonyl_C",
        "expected_unit": "N...C(=O)",
        "usage": "sequence monomer; counted as peptide-like residue",
    },
    "linker": {
        "chain_in": "amine_N",
        "chain_out": "carbonyl_C",
        "expected_unit": "N...C(=O)",
        "usage": "linear spacer/linker; not STD AA",
    },
    "label": {
        "chain_in": "label_amine_N",
        "chain_out": None,
        "expected_unit": "N-label_fragment",
        "usage": "terminal or side-chain modification; not sequence residue",
    },
    "chemical": {
        "chain_in": "chemical_amine_or_linker_N",
        "chain_out": "optional_carbonyl_C_or_none",
        "expected_unit": "N-chemical_fragment or N...C(=O)",
        "usage": "chemical modification such as lipid/cholesterol handle; not sequence residue",
    },
}

TEMPLATE_READY_REGISTRY: Dict[str, Dict[str, Any]] = {}
for _tok, _smiles in {**NON_NATURAL_UNITS, **LINKER_UNITS, **LABEL_UNITS, **CHEMICAL_UNITS}.items():
    if _tok in NON_NATURAL_UNITS:
        _cat = "non_natural_aa"
    elif _tok in LINKER_UNITS:
        _cat = "linker"
    elif _tok in LABEL_UNITS:
        _cat = "label"
    else:
        _cat = "chemical"
    TEMPLATE_READY_REGISTRY[_tok] = {
        "token": _tok,
        "category": _cat,
        "source": "rdkit_template_sdf_checked_v130",
        "smiles": _smiles,
        "template_file": f"pepforge_structure_tool/data/templates/{_tok}.sdf",
        "attach_points": TEMPLATE_ATTACHMENT_RULES[_cat],
        "local_attach_atom_hints": _infer_local_attach_points(_smiles, _cat),
        "template_swap_rule": "Curated SDF may replace the placeholder if it keeps the same attach-point roles and local attach atom hints are updated when needed.",
        "curation_status": "template_file_checked_and_attach_hint_mapped; replace with curated SDF for publication-grade geometry",
    }

def template_manifest() -> Dict[str, Any]:
    return {
        "version": VERSION,
        "template_mode": "attachment_aware_template_checked_v130",
        "important_limit": "Structures are RDKit-generated connected starting models with template SDF audit. Template files can be replaced by curated SDFs while preserving token syntax.",
        "attach_point_rules": TEMPLATE_ATTACHMENT_RULES,
        "templates": TEMPLATE_READY_REGISTRY,
    }

def supported_token_table() -> Dict[str, Any]:
    """Return supported tokens grouped by Pepforge interpretation category."""
    return {
        "version": VERSION,
        "std_aa": sorted(STD_AA),
        "d_std_aa": sorted('d' + aa for aa in STD_AA),
        "non_natural_aa": sorted(NON_NATURAL_UNITS),
        "linker": sorted(LINKER_UNITS),
        "label": sorted(LABEL_UNITS),
        "chemical": sorted(CHEMICAL_UNITS),
        "n_terminal": sorted(N_TERMINAL_CAPS),
        "c_terminal": sorted(C_TERMINAL_CAPS),
        "tag_expansion": sorted(TAG_EXPANSIONS),
        "aliases": dict(sorted(TOKEN_ALIASES.items())),
        "sidechain_acceptors": sorted(SIDECHAIN_ACCEPTORS),
        "fixed_rule": "STD remains 20 canonical residues; Biotin/FITC/Cy5 are labels; Ahx/PEG/AEEA are linkers; Pal/Myr/Chol are chemical modifications.",
        "template_registry": TEMPLATE_READY_REGISTRY,
        "template_manifest": template_manifest(),
    }

def environment_report() -> Dict[str, Any]:
    """Return a compact runtime report for PyMOL/standalone troubleshooting."""
    report: Dict[str, Any] = {
        "pepforge_version": VERSION,
        "rdkit_available": Chem is not None,
        "rdkit_import_error": str(_RDKIT_IMPORT_ERROR) if _RDKIT_IMPORT_ERROR else None,
        "supported_counts": {},
    }
    if Chem is not None:
        try:
            import rdkit
            report["rdkit_version"] = getattr(rdkit, "__version__", "unknown")
        except Exception:
            report["rdkit_version"] = "unknown"
    table = supported_token_table()
    for k in ["std_aa", "d_std_aa", "non_natural_aa", "linker", "label", "chemical", "n_terminal", "c_terminal", "tag_expansion", "aliases"]:
        report["supported_counts"][k] = len(table.get(k, {}))
    return report

def _chemistry_audit(mol, tokens: List[Token], smiles: str) -> Dict[str, Any]:
    """Lightweight sanity report for generated starting models."""
    audit: Dict[str, Any] = {
        "valid_molecule": mol is not None,
        "generated_smiles_parseable": bool(smiles),
        "connected_components": None,
        "formal_charge": None,
        "chiral_centers": [],
        "num_conformers": None,
        "sequence_like_token_count": sum(t.kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"} for t in tokens),
        "label_token_count": sum(t.kind == "label" for t in tokens),
        "linker_token_count": sum(t.kind == "linker" for t in tokens),
        "chemical_token_count": sum(t.kind == "chemical" for t in tokens),
    }
    if mol is None or Chem is None:
        return audit
    try:
        frags = Chem.GetMolFrags(mol)
        audit["connected_components"] = len(frags)
    except Exception:
        pass
    try:
        audit["formal_charge"] = int(sum(a.GetFormalCharge() for a in mol.GetAtoms()))
    except Exception:
        pass
    try:
        audit["chiral_centers"] = Chem.FindMolChiralCenters(mol, includeUnassigned=True)
    except Exception:
        pass
    try:
        audit["num_conformers"] = int(mol.GetNumConformers())
    except Exception:
        pass
    return audit

@dataclass
class Token:
    raw: str
    kind: str
    unit_smiles: Optional[str] = None
    note: str = ""
    expanded_from: Optional[str] = None
    heavy_atom_count: int = 0
    parent_residue: Optional[str] = None
    modification: Optional[str] = None

@dataclass
class AtomRange:
    token: str
    kind: str
    label: str
    heavy_start_1based: int
    heavy_end_1based: int
    note: str = ""

@dataclass
class BuildResult:
    input_text: str
    tokens: List[Token]
    smiles: str
    molblock: Optional[str]
    sdf_path: Optional[str]
    pdb_path: Optional[str]
    meta_path: Optional[str]
    report_path: Optional[str] = None
    warnings: List[str] = field(default_factory=list)
    formula: Optional[str] = None
    exact_mw: Optional[float] = None
    heavy_atoms: Optional[int] = None
    atom_ranges: List[AtomRange] = field(default_factory=list)

class PepforgeBuildError(RuntimeError):
    pass

# -----------------------------------------------------------------------------
# Utility / parser
# -----------------------------------------------------------------------------
def _require_rdkit() -> None:
    if Chem is None:
        raise PepforgeBuildError(
            "RDKit is required for 3D structure generation but could not be imported. "
            f"Import error: {_RDKIT_IMPORT_ERROR}"
        )

def _heavy_count(smiles: Optional[str]) -> int:
    if not smiles or Chem is None:
        return 0
    m = Chem.MolFromSmiles(smiles)
    return m.GetNumHeavyAtoms() if m is not None else 0



def _infer_local_attach_points(smiles: Optional[str], category: str) -> Dict[str, Optional[int]]:
    """Infer 1-based heavy-atom ranks used as attach-site hints.

    This is not a quantum/curated geometry claim. It gives the builder and PyMOL
    an explicit, auditable map of the atoms that represent the chain-in and
    chain-out sites inside each token/template unit. Curated SDF replacement
    files should preserve these roles or update the manifest accordingly.
    """
    result: Dict[str, Optional[int]] = {"in_atom_1based": None, "out_atom_1based": None}
    if not smiles or Chem is None:
        return result
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return result
    # first nitrogen is normally the connection entering the unit
    for a in mol.GetAtoms():
        if a.GetAtomicNum() == 7:
            result["in_atom_1based"] = int(a.GetIdx()) + 1
            break
    # choose the last carbonyl carbon as chain-out for peptide-like/linker/chemical units
    carbonyls = []
    for a in mol.GetAtoms():
        if a.GetAtomicNum() != 6:
            continue
        for b in a.GetBonds():
            other = b.GetOtherAtom(a)
            if other.GetAtomicNum() == 8 and int(b.GetBondTypeAsDouble()) == 2:
                carbonyls.append(int(a.GetIdx()) + 1)
                break
    if category in {"std_aa", "d_std_aa", "sidechain_label_aa", "non_natural_aa", "linker", "chemical", "n_terminal"} and carbonyls:
        result["out_atom_1based"] = max(carbonyls)
    if category == "label":
        result["out_atom_1based"] = None
    return result


def _global_attach_points_for_range(token: Token, atom_range: 'AtomRange') -> Dict[str, Any]:
    local = _infer_local_attach_points(token.unit_smiles, token.kind)
    out: Dict[str, Any] = {
        "token": token.raw,
        "kind": token.kind,
        "parent_residue": token.parent_residue,
        "modification": token.modification,
        "range_heavy_1based": [atom_range.heavy_start_1based, atom_range.heavy_end_1based],
        "local_in_atom_1based": local.get("in_atom_1based"),
        "local_out_atom_1based": local.get("out_atom_1based"),
        "global_in_atom_1based": None,
        "global_out_atom_1based": None,
        "role_note": "Attach-site hint based on token/template atom ranks. Use curated SDF + updated manifest for publication-grade geometry.",
    }
    if local.get("in_atom_1based"):
        out["global_in_atom_1based"] = atom_range.heavy_start_1based + int(local["in_atom_1based"]) - 1
    if local.get("out_atom_1based"):
        out["global_out_atom_1based"] = atom_range.heavy_start_1based + int(local["out_atom_1based"]) - 1
    return out


def _build_attach_point_map(tokens: List[Token], atom_ranges: List['AtomRange']) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for tok, ar in zip([t for t in tokens if t.kind != "c_terminal"], atom_ranges):
        if tok.kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa", "linker", "label", "chemical", "n_terminal"}:
            out.append(_global_attach_points_for_range(tok, ar))
    return out

def _strip_outer_brackets(piece: str) -> str:
    piece = piece.strip()
    if piece.startswith("[") and piece.endswith("]"):
        return piece[1:-1].strip()
    return piece

def _split_top_level(text: str) -> List[str]:
    text = text.strip().replace(" ", "")
    if not text:
        return []
    out, buf = [], ""
    bracket = 0
    paren = 0
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "[":
            bracket += 1
            if bracket == 1:
                if buf:
                    out.append(buf); buf = ""
                i += 1; continue
        if ch == "]":
            bracket -= 1
            if bracket < 0: raise PepforgeBuildError("Unmatched ']' in sequence input.")
            if bracket == 0:
                out.append(buf); buf = ""
                i += 1; continue
        if bracket == 0:
            if ch == "(": paren += 1
            elif ch == ")":
                paren -= 1
                if paren < 0: raise PepforgeBuildError("Unmatched ')' in sequence input.")
            elif ch in "-|_" and paren == 0:
                if buf:
                    out.append(buf); buf = ""
                i += 1; continue
        buf += ch
        i += 1
    if bracket != 0: raise PepforgeBuildError("Unclosed '[' in sequence input.")
    if paren != 0: raise PepforgeBuildError("Unclosed '(' in sequence input.")
    if buf: out.append(buf)
    return [_strip_outer_brackets(x) for x in out if x]

_SIDECHAIN_RE = re.compile(r"^(d?[A-Z]|d?[A-Z][a-z]{2}|Aib|Nle|dNle|Orn|dOrn|Dab|dDab|Cit|dCit|Hyp|dHyp|Cha|dCha|Nal|dNal)\((.+)\)$")

def is_sidechain_token(piece: str) -> bool:
    return bool(_SIDECHAIN_RE.match(piece))

def _alias_key(tok: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", str(tok or "")).lower()

def _normalize_token(tok: str) -> str:
    if tok in TOKEN_ALIASES:
        return TOKEN_ALIASES[tok]
    key = _alias_key(tok)
    for alias, canonical in TOKEN_ALIASES.items():
        if _alias_key(alias) == key:
            return canonical
    return tok

def _normalize_sidechain_token(tok: str) -> str:
    m = _SIDECHAIN_RE.match(tok)
    if not m:
        return _normalize_token(tok)
    parent, mod = m.group(1), m.group(2)
    parts = [_normalize_token(x) for x in _split_top_level(mod.replace(",", "-"))]
    return f"{_normalize_token(parent)}({'-'.join(parts)})"

def _tokenize_piece(piece: str) -> List[str]:
    if not piece:
        return []
    if is_sidechain_token(piece):
        return [_normalize_sidechain_token(piece)]
    norm_piece = _normalize_token(piece)
    if norm_piece in KNOWN_MULTI_TOKENS or norm_piece in STD_AA:
        return [norm_piece]
    if piece.startswith("d") and len(piece) == 2 and piece[1] in STD_AA:
        return [piece]
    tokens: List[str] = []
    i = 0
    while i < len(piece):
        # Side-chain modification inside a compact sequence, e.g. AK(FITC)LVFF
        m = re.match(r"(d?[A-Z]|Orn|Dab|Nle|Aib|Cit|Hyp|Cha|Nal)\(([^()]+)\)", piece[i:])
        if m:
            tokens.append(m.group(0)); i += len(m.group(0)); continue
        matched = None
        matched_len = 0
        for tok in KNOWN_MULTI_TOKENS:
            if piece[i:].lower().startswith(str(tok).lower()):
                matched = tok; matched_len = len(tok); break
        if not matched:
            compact_tail = re.sub(r"[^A-Za-z0-9]", "", piece[i:]).lower()
            for alias, canonical in sorted(TOKEN_ALIASES.items(), key=lambda kv: len(re.sub(r"[^A-Za-z0-9]", "", kv[0])), reverse=True):
                alias_key = _alias_key(alias)
                if compact_tail.startswith(alias_key):
                    matched = canonical; matched_len = len(alias_key); break
        if matched:
            tokens.append(matched); i += max(1, matched_len); continue
        if piece[i] == "d" and i + 1 < len(piece) and piece[i + 1] in STD_AA:
            tokens.append(piece[i:i+2]); i += 2; continue
        if piece[i] in STD_AA:
            tokens.append(piece[i]); i += 1; continue
        raise PepforgeBuildError(f"Unknown token near '{piece[i:]}' in '{piece}'. Use brackets for multi-letter tokens, e.g. [Aib] or K(FITC).")
    return tokens

def expand_and_tokenize(text: str) -> List[str]:
    raw_parts = _split_top_level(text)
    tokens: List[str] = []
    for part in raw_parts:
        if part in TAG_EXPANSIONS:
            for aa in TAG_EXPANSIONS[part]:
                tokens.append(aa)
        else:
            tokens.extend(_tokenize_piece(part))
    return tokens

def _sidechain_linkage_smiles(parent: str, mods: str) -> str:
    """Return a simplified residue unit for side-chain modification.
    K/Orn/Dab: side-chain amide/urea-like linkage via terminal amine.
    C: thioether-like visualization linkage via sulfur.
    mods can be Label or Linker-Label, e.g. FITC or Ahx-Biotin.
    """
    if parent not in SIDECHAIN_ACCEPTORS:
        raise PepforgeBuildError(f"Side-chain modification is currently supported for {sorted(SIDECHAIN_ACCEPTORS)}, not '{parent}'.")
    parts = _split_top_level(mods.replace(",", "-"))
    if not parts:
        raise PepforgeBuildError("Empty side-chain modification.")
    for p in parts:
        if p not in LINKER_UNITS and p not in LABEL_UNITS and p not in CHEMICAL_UNITS:
            raise PepforgeBuildError(f"Unsupported side-chain modification token '{p}'. Use known linker/label/chemical names such as Ahx, PEG4, Biotin, FITC, Pal, Chol.")
    # If an acyl lipid is attached through a side-chain amine, the amide
    # carbonyl is supplied by the linkage below. Therefore Pal/Myr/Ste/Lau use
    # hydrocarbon tails here, not the generic N...C(=O) display fragment.
    tail = "".join((
        LINKER_UNITS[p] if p in LINKER_UNITS else
        LABEL_UNITS[p] if p in LABEL_UNITS else
        SIDECHAIN_ACYL_TAILS[p] if p in SIDECHAIN_ACYL_TAILS else
        CHEMICAL_UNITS[p]
    ) for p in parts)
    is_d = parent.startswith("d")
    base = parent[1:] if is_d else parent
    chiral = "@H" if is_d else "@@H"
    if base == "K":
        return f"N[C{chiral}](CCCCNC(=O){tail})C(=O)"
    if base == "Orn":
        return f"N[C{chiral}](CCCNC(=O){tail})C(=O)"
    if base == "Dab":
        return f"N[C{chiral}](CCNC(=O){tail})C(=O)"
    if base == "C":
        # Simplified thioether / thiourea-like display connection.
        return f"N[C{chiral}](CSC(=O){tail})C(=O)"
    raise PepforgeBuildError(f"Unsupported side-chain modification parent '{parent}'.")

def classify_token(tok: str) -> Token:
    sm = _SIDECHAIN_RE.match(tok)
    if sm:
        parent, mod = sm.group(1), sm.group(2)
        unit = _sidechain_linkage_smiles(parent, mod)
        return Token(tok, "sidechain_label_aa", unit, note=f"side-chain modification on {parent}; modification is not sequence residue", heavy_atom_count=_heavy_count(unit), parent_residue=parent, modification=mod)
    if tok in N_TERMINAL_CAPS:
        return Token(tok, "n_terminal", N_TERMINAL_CAPS[tok], heavy_atom_count=_heavy_count(N_TERMINAL_CAPS[tok]))
    if tok in C_TERMINAL_CAPS:
        return Token(tok, "c_terminal", None, heavy_atom_count=0)
    if tok.startswith("d") and len(tok) == 2 and tok[1] in D_RESIDUE_UNITS:
        smi = D_RESIDUE_UNITS[tok[1]]
        return Token(tok, "d_std_aa", smi, heavy_atom_count=_heavy_count(smi))
    if tok in L_RESIDUE_UNITS:
        smi = L_RESIDUE_UNITS[tok]
        return Token(tok, "std_aa", smi, heavy_atom_count=_heavy_count(smi))
    if tok in NON_NATURAL_UNITS:
        smi = NON_NATURAL_UNITS[tok]
        return Token(tok, "non_natural_aa", smi, heavy_atom_count=_heavy_count(smi))
    if tok in LINKER_UNITS:
        smi = LINKER_UNITS[tok]
        return Token(tok, "linker", smi, note="linker; not counted as STD peptide residue", heavy_atom_count=_heavy_count(smi))
    if tok in LABEL_UNITS:
        smi = LABEL_UNITS[tok]
        return Token(tok, "label", smi, note="label; not counted as peptide sequence residue", heavy_atom_count=_heavy_count(smi))
    if tok in CHEMICAL_UNITS:
        smi = CHEMICAL_UNITS[tok]
        return Token(tok, "chemical", smi, note="chemical modification; not counted as peptide sequence residue", heavy_atom_count=_heavy_count(smi))
    raise PepforgeBuildError(f"Unsupported token: {tok}")

# -----------------------------------------------------------------------------
# Validation / building
# -----------------------------------------------------------------------------
def validate_tokens(tokens: List[Token]) -> List[str]:
    warnings: List[str] = []
    # Leading Pal/Myr/Ste/Lau are intentional N-terminal acyl caps and should
    # not be warned as free terminal labels. Other labels/chemicals still get
    # conservative linker/placement warnings.
    labels = [t for i, t in enumerate(tokens) if t.kind in {"label", "chemical"} and not (i == 0 and t.raw in N_TERMINAL_ACYL_CHEM_CAPS)]
    linkers = [t for t in tokens if t.kind == "linker"]
    seq_like = [t for t in tokens if t.kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"}]
    if labels and not linkers and len(seq_like) > 0:
        warnings.append("Terminal label is directly connected without an explicit linker. Add Ahx/PEG4 if the wet-lab design uses a spacer.")
    for i, t in enumerate(tokens[:-1]):
        if i == 0 and t.kind == "chemical" and t.raw in N_TERMINAL_ACYL_CHEM_CAPS and tokens[i+1].kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"}:
            continue
        if t.kind in {"label", "chemical"} and tokens[i+1].kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"}:
            warnings.append(f"Modification '{t.raw}' is followed by sequence residue '{tokens[i+1].raw}'. In Pepforge rules labels are modifications, not STD sequence residues; check whether a linker/terminal placement was intended.")
        if t.kind == "linker" and tokens[i+1].kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"}:
            warnings.append(f"Linker '{t.raw}' is followed by sequence residue '{tokens[i+1].raw}'. This is allowed as a connected model, but verify N-to-C direction.")
    for i, t in enumerate(tokens):
        if t.kind == "n_terminal" and any(x.kind in {"std_aa","d_std_aa","non_natural_aa","sidechain_label_aa","linker","label"} for x in tokens[:i]):
            warnings.append(f"N-terminal cap '{t.raw}' appears after buildable units; chemistry may not match intent.")
        if t.kind == "c_terminal" and i != len(tokens)-1:
            warnings.append(f"C-terminal cap '{t.raw}' appears before the end; treated as terminal annotation.")
    if len([t for t in tokens if t.kind == "n_terminal"]) > 1:
        warnings.append("Multiple N-terminal caps were supplied; first one is used for chemistry.")
    if len([t for t in tokens if t.kind == "c_terminal"]) > 1:
        warnings.append("Multiple C-terminal caps were supplied; last one is used.")
    return warnings

def tokens_to_smiles(tokens_raw: List[str]) -> Tuple[str, List[Token], List[str], List[AtomRange]]:
    if not tokens_raw:
        raise PepforgeBuildError("Empty sequence input.")
    tokens = [classify_token(t) for t in tokens_raw]
    warnings: List[str] = validate_tokens(tokens)
    atom_ranges: List[AtomRange] = []

    ncap = ""
    ncap_token: Optional[Token] = None
    cterm = "OH"
    chain_units: List[Token] = []
    seen_sequence_like = False
    seen_c_terminal_label = False

    for tok in tokens:
        if tok.kind == "n_terminal":
            if seen_sequence_like:
                warnings.append(f"N-terminal cap '{tok.raw}' appeared after sequence start; ignored as chemistry in v1.3.")
            elif ncap:
                warnings.append(f"Multiple N-terminal caps found; using first cap and ignoring '{tok.raw}'.")
            else:
                ncap = tok.unit_smiles or ""; ncap_token = tok
            continue
        if tok.kind == "c_terminal":
            cterm = tok.raw
            continue

        # v2.0.0 hotfix:
        # Leading lipid chemical tokens such as Pal/Myr/Ste/Lau are N-terminal
        # acyl caps, not sequence/label units. This prevents Pal-dG-dH-dK-NH2
        # from being built as an amino-palmitoyl-like fragment and keeps the
        # C-terminal NH2 as a real amide atom.
        if tok.kind == "chemical" and tok.raw in N_TERMINAL_ACYL_CHEM_CAPS and not seen_sequence_like and not chain_units:
            if ncap:
                warnings.append(f"N-terminal acyl token '{tok.raw}' was supplied after another N-cap; kept as generic chemical unit.")
                chain_units.append(tok)
            else:
                ncap = N_TERMINAL_ACYL_CHEM_CAPS[tok.raw]
                ncap_token = Token(tok.raw, "n_terminal", ncap, note=f"N-terminal {tok.raw} acyl cap; fixed v2.0.0 hotfix", heavy_atom_count=_heavy_count(ncap))
            continue

        if tok.kind in {"label", "chemical"}:
            if seen_sequence_like:
                seen_c_terminal_label = True
            chain_units.append(tok)
            continue
        if tok.kind == "linker":
            seen_sequence_like = True
            chain_units.append(tok)
            continue
        if tok.kind in {"std_aa", "d_std_aa", "non_natural_aa", "sidechain_label_aa"}:
            if seen_c_terminal_label:
                warnings.append(f"Residue '{tok.raw}' appears after a terminal label. Model remains connected, but check intended chemistry.")
            seen_sequence_like = True
            chain_units.append(tok)
            continue

    if not chain_units:
        raise PepforgeBuildError("No buildable peptide/linker/label units found.")

    smiles_parts: List[str] = []
    cursor = 1
    if ncap:
        smiles_parts.append(ncap)
        n = _heavy_count(ncap)
        atom_ranges.append(AtomRange(ncap_token.raw if ncap_token else "Ncap", "n_terminal", KIND_LABELS["n_terminal"], cursor, cursor + n - 1, ncap_token.note if ncap_token else ""))
        cursor += n

    for tok in chain_units:
        smiles_parts.append(tok.unit_smiles or "")
        n = tok.heavy_atom_count or _heavy_count(tok.unit_smiles)
        atom_ranges.append(AtomRange(tok.raw, tok.kind, KIND_LABELS.get(tok.kind, tok.kind), cursor, cursor + n - 1, tok.note))
        cursor += n

    # Always materialize the requested C-terminal cap as the terminal atom for
    # ordinary peptide/linker chains. Only true C-terminal labels remain as
    # annotation-level chemistry because the label itself is the terminal unit.
    if seen_c_terminal_label:
        if cterm != "OH":
            warnings.append(f"C-terminal cap '{cterm}' was specified after a terminal label/chemical unit. The terminal label remains connected; cap is annotation-only.")
    else:
        terminal_atom = "N" if cterm == "NH2" else "O"
        smiles_parts.append(terminal_atom)
        atom_ranges.append(AtomRange(cterm, "c_terminal_atom", KIND_LABELS["c_terminal"], cursor, cursor, "terminal atom added to last carbonyl"))
        cursor += 1

    return "".join(smiles_parts), tokens, warnings, atom_ranges

def _add_mol_properties(mol, sequence: str, tokens: List[Token], atom_ranges: List[AtomRange], warnings: List[str], name: str) -> None:
    mol.SetProp("_Name", name)
    mol.SetProp("Pepforge_Version", VERSION)
    mol.SetProp("Pepforge_Input", sequence)
    mol.SetProp("Pepforge_Tokens", "|".join(t.raw for t in tokens))
    mol.SetProp("Pepforge_Token_Kinds", "|".join(t.kind for t in tokens))
    mol.SetProp("Pepforge_Atom_Ranges", json.dumps([asdict(r) for r in atom_ranges], ensure_ascii=False))
    mol.SetProp("Pepforge_Warnings", " | ".join(warnings))
    mol.SetProp("Pepforge_Notice", "Labels are modifications, not peptide sequence residues. Linkers are spacer units, not STD residues.")

def audit_template_files(base_dir: str | Path | None = None) -> Dict[str, Any]:
    """Check template SDF files for template-capable tokens.

    This does not claim experimental curation. It verifies that PyMOL/RDKit-readable
    SDF templates exist and records formula/heavy atom counts for replacement-ready
    curation workflows.
    """
    base = Path(base_dir) if base_dir else Path(__file__).resolve().parents[1]
    records = []
    ok = 0
    missing = 0
    unreadable = 0
    for tok, rec in sorted(TEMPLATE_READY_REGISTRY.items()):
        rel = rec.get("template_file", "")
        path = base / rel
        row = dict(rec)
        row["template_abs_path"] = str(path)
        row["exists"] = path.exists()
        row["readable_by_rdkit"] = False
        row["template_formula"] = None
        row["template_heavy_atoms"] = None
        if not path.exists():
            missing += 1
        elif Chem is None:
            unreadable += 1
            row["read_error"] = "RDKit not available"
        else:
            try:
                suppl = Chem.SDMolSupplier(str(path), removeHs=False)
                mol = suppl[0] if len(suppl) else None
                if mol is None:
                    unreadable += 1
                    row["read_error"] = "RDKit returned None"
                else:
                    ok += 1
                    row["readable_by_rdkit"] = True
                    row["template_formula"] = rdMolDescriptors.CalcMolFormula(mol)
                    row["template_heavy_atoms"] = int(mol.GetNumHeavyAtoms())
            except Exception as exc:
                unreadable += 1
                row["read_error"] = str(exc)
        records.append(row)
    return {
        "version": VERSION,
        "template_mode": "attachment_aware_template_checked_v130",
        "summary": {"total": len(records), "ok": ok, "missing": missing, "unreadable": unreadable},
        "records": records,
    }


def _template_audit_for_tokens(tokens: List[Token], base_dir: str | Path | None = None) -> List[Dict[str, Any]]:
    full = audit_template_files(base_dir)
    by_token = {r.get("token"): r for r in full.get("records", [])}
    out = []
    for t in tokens:
        out.append(by_token.get(t.raw, {"token": t.raw, "category": t.kind, "source": "inline_or_terminal", "exists": None, "readable_by_rdkit": None}))
    return out

def make_report(meta: Dict[str, Any]) -> str:
    lines = []
    lines.append(f"Pepforge PyMOL Structure Tool v{meta.get('version')} report")
    lines.append("=" * 64)
    lines.append(f"Input: {meta.get('input')}")
    lines.append(f"Formula: {meta.get('formula')}")
    lines.append(f"Exact MW: {meta.get('exact_mw')}")
    lines.append(f"Heavy atoms: {meta.get('heavy_atoms')}")
    lines.append("")
    lines.append("Category counts:")
    for k, v in sorted((meta.get('category_counts') or {}).items()):
        lines.append(f"  - {k}: {v}")
    lines.append("")
    lines.append("Token / atom-range map:")
    for r in meta.get('atom_ranges', []):
        lines.append(f"  - {r.get('token'):>16s} | {r.get('kind'):<18s} | heavy rank {r.get('heavy_start_1based')}-{r.get('heavy_end_1based')} | {r.get('note','')}")
    lines.append("")
    lines.append("Attach-point map:")
    for ap in meta.get('attach_point_map', []):
        lines.append(f"  - {ap.get('token'):>16s} | {ap.get('kind'):<18s} | IN global {ap.get('global_in_atom_1based')} | OUT global {ap.get('global_out_atom_1based')}")
    lines.append("")
    lines.append("Chemistry audit:")
    audit = meta.get('chemistry_audit') or {}
    for k, v in audit.items():
        lines.append(f"  - {k}: {v}")
    lines.append("")
    lines.append("Conformer summary:")
    conf = meta.get('conformer_summary') or {}
    for k, v in conf.items():
        if k == 'energies':
            lines.append(f"  - energies: {len(v)} conformer record(s)")
        else:
            lines.append(f"  - {k}: {v}")
    lines.append("")
    lines.append("Template mode:")
    lines.append(f"  - {meta.get('template_mode')}")
    lines.append(f"  - {meta.get('template_registry_notice')}")
    ta = meta.get('template_audit') or []
    if ta:
        lines.append("Template audit:")
        for rec in ta:
            token = rec.get('token')
            category = rec.get('category')
            source = rec.get('source')
            curation = rec.get('curation_status', '')
            template_file = rec.get('template_file', '')
            lines.append(f"  - {token}: {category} | {source} | {template_file} | {curation}")
    lines.append("")
    lines.append("Warnings:")
    ws = meta.get('warnings') or []
    if ws:
        for w in ws: lines.append(f"  - {w}")
    else:
        lines.append("  - none")
    lines.append("")
    lines.append("Fixed interpretation rule:")
    lines.append("  Biotin/FITC/Cy5/FAM/TAMRA are labels/modifications, not peptide sequence residues.")
    lines.append("  Ahx/PEG/AEEA are linkers/spacers, not STD residues. Pal/Myr/Chol are chemical modifications, not residues.")
    lines.append("  Leading Pal/Myr/Ste/Lau are built as N-terminal acyl caps; terminal NH2 is built as C-terminal amide atom.")
    lines.append("  STD AA remains the 20 canonical amino acids; dX means D-form where X is canonical.")
    return "\n".join(lines) + "\n"


def _energy_for_conformer(mol, conf_id: int = 0) -> Optional[float]:
    """Return approximate force-field energy for an embedded conformer."""
    if Chem is None or AllChem is None or mol is None:
        return None
    try:
        if AllChem.MMFFHasAllMoleculeParams(mol):
            props = AllChem.MMFFGetMoleculeProperties(mol)
            ff = AllChem.MMFFGetMoleculeForceField(mol, props, confId=int(conf_id))
        else:
            ff = AllChem.UFFGetMoleculeForceField(mol, confId=int(conf_id))
        return float(ff.CalcEnergy()) if ff is not None else None
    except Exception:
        return None


def _optimize_conformers(mol, conf_ids: List[int], max_iters: int, warnings: List[str]) -> Dict[str, Any]:
    """Optimize conformers and return best conformer/energy summary."""
    summary: Dict[str, Any] = {
        "requested_conformers": len(conf_ids),
        "embedded_conformers": len(conf_ids),
        "best_conf_id": None,
        "best_energy": None,
        "energy_unit": "RDKit force-field arbitrary/mol units; compare within same molecule only",
        "method": None,
        "energies": [],
    }
    if not conf_ids:
        return summary
    use_mmff = False
    try:
        use_mmff = bool(AllChem.MMFFHasAllMoleculeParams(mol))
    except Exception:
        use_mmff = False
    summary["method"] = "MMFF94" if use_mmff else "UFF"
    if not use_mmff:
        warnings.append("MMFF parameters incomplete; using UFF optimization/energy ranking.")
    try:
        if use_mmff:
            results = AllChem.MMFFOptimizeMoleculeConfs(mol, maxIters=int(max_iters), numThreads=0)
        else:
            results = AllChem.UFFOptimizeMoleculeConfs(mol, maxIters=int(max_iters), numThreads=0)
        for conf_id, result in zip(conf_ids, results):
            not_converged, energy = result
            if int(not_converged) != 0:
                warnings.append(f"Conformer {conf_id} did not fully converge within max iterations.")
            summary["energies"].append({"conf_id": int(conf_id), "energy": float(energy), "not_converged": int(not_converged)})
    except Exception as exc:
        warnings.append(f"Conformer optimization warning: {exc}")
        for conf_id in conf_ids:
            summary["energies"].append({"conf_id": int(conf_id), "energy": _energy_for_conformer(mol, conf_id), "not_converged": None})
    valid = [e for e in summary["energies"] if e.get("energy") is not None]
    if valid:
        best = min(valid, key=lambda x: x["energy"])
        summary["best_conf_id"] = int(best["conf_id"])
        summary["best_energy"] = float(best["energy"])
    return summary


def _copy_best_conformer_only(mol, best_conf_id: Optional[int]):
    """Return a molecule retaining only the best conformer for cleaner SDF/PDB export."""
    if best_conf_id is None:
        return mol
    try:
        new = Chem.Mol(mol)
        conf = mol.GetConformer(int(best_conf_id))
        new.RemoveAllConformers()
        new.AddConformer(conf, assignId=True)
        return new
    except Exception:
        return mol

def build_structure(
    sequence: str,
    output_dir: str | Path = ".",
    name: str = "pepforge_structure",
    seed: int = 61453,
    optimize: bool = True,
    max_iters: int = 1000,
    num_confs: int = 8,
    keep_all_confs: bool = False,
) -> BuildResult:
    _require_rdkit()
    outdir = Path(output_dir); outdir.mkdir(parents=True, exist_ok=True)
    raw_tokens = expand_and_tokenize(sequence)
    smiles, tokens, warnings, atom_ranges = tokens_to_smiles(raw_tokens)

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise PepforgeBuildError(f"RDKit failed to parse generated SMILES: {smiles}")
    _add_mol_properties(mol, sequence, tokens, atom_ranges, warnings, name)

    mol_h = Chem.AddHs(mol, addCoords=True)
    _add_mol_properties(mol_h, sequence, tokens, atom_ranges, warnings, name)

    params = AllChem.ETKDGv3()
    params.randomSeed = int(seed)
    params.useSmallRingTorsions = True
    params.useMacrocycleTorsions = True
    params.enforceChirality = True
    try:
        params.pruneRmsThresh = 0.5
    except Exception:
        pass

    requested_confs = max(1, int(num_confs or 1))
    conf_ids = list(AllChem.EmbedMultipleConfs(mol_h, numConfs=requested_confs, params=params))
    if not conf_ids:
        warnings.append("ETKDG multi-conformer embedding failed; retrying one conformer with random coordinates.")
        params.useRandomCoords = True
        conf_id = AllChem.EmbedMolecule(mol_h, params)
        if conf_id < 0:
            raise PepforgeBuildError("RDKit could not generate a 3D conformer for this input.")
        conf_ids = [int(conf_id)]

    conformer_summary = {
        "requested_conformers": requested_confs,
        "embedded_conformers": len(conf_ids),
        "best_conf_id": int(conf_ids[0]) if conf_ids else None,
        "best_energy": None,
        "energy_unit": "not optimized",
        "method": "ETKDG only",
        "energies": [],
    }
    if optimize:
        conformer_summary = _optimize_conformers(mol_h, conf_ids, max_iters, warnings)

    mol_export = mol_h if keep_all_confs else _copy_best_conformer_only(mol_h, conformer_summary.get("best_conf_id"))
    _add_mol_properties(mol_export, sequence, tokens, atom_ranges, warnings, name)
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("_") or "pepforge_structure"
    sdf_path = outdir / f"{safe}.sdf"
    pdb_path = outdir / f"{safe}.pdb"
    meta_path = outdir / f"{safe}.json"
    report_path = outdir / f"{safe}_report.txt"

    # v4.2.0 functional stability fix:
    # RDKit's C++ file writers can fail on some Windows user/temp paths.
    # If SDWriter/MolToPDBFile refuses the output path, fall back to Python-level
    # text writing from MolBlock/PDBBlock. This is more tolerant of Unicode paths.
    try:
        writer = Chem.SDWriter(str(sdf_path))
        if writer is None:
            raise OSError(f"RDKit SDWriter returned None for {sdf_path}")
        if keep_all_confs:
            for cid in range(mol_export.GetNumConformers()):
                writer.write(mol_export, confId=cid)
        else:
            writer.write(mol_export)
        writer.close()
    except Exception as exc:
        warnings.append(f"RDKit SDWriter path fallback used: {exc}")
        if keep_all_confs and mol_export.GetNumConformers() > 1:
            blocks = []
            for cid in range(mol_export.GetNumConformers()):
                blocks.append(Chem.MolToMolBlock(mol_export, confId=cid) + "\n$$$$\n")
            sdf_path.write_text("".join(blocks), encoding="utf-8", errors="ignore")
        else:
            sdf_path.write_text(Chem.MolToMolBlock(mol_export) + "\n$$$$\n", encoding="utf-8", errors="ignore")
    try:
        Chem.MolToPDBFile(mol_export, str(pdb_path))
    except Exception as exc:
        warnings.append(f"RDKit PDB writer path fallback used: {exc}")
        pdb_path.write_text(Chem.MolToPDBBlock(mol_export), encoding="utf-8", errors="ignore")

    audit = _chemistry_audit(mol_export, tokens, smiles)
    attach_point_map = _build_attach_point_map(tokens, atom_ranges)

    meta: Dict[str, Any] = {
        "version": VERSION,
        "input": sequence,
        "tokens": [asdict(t) for t in tokens],
        "generated_smiles": smiles,
        "warnings": warnings,
        "formula": rdMolDescriptors.CalcMolFormula(mol_export),
        "exact_mw": float(Descriptors.ExactMolWt(mol_export)),
        "heavy_atoms": int(mol.GetNumHeavyAtoms()),
        "atom_ranges": [asdict(r) for r in atom_ranges],
        "attach_point_map": attach_point_map,
        "category_counts": {},
        "chemistry_audit": audit,
        "conformer_summary": conformer_summary,
        "template_mode": "attachment_aware_template_checked_v130",
        "template_audit": _template_audit_for_tokens(tokens),
        "template_registry_notice": "v1.3.0 adds attach-point manifest + placeholder SDF templates. Replace data/templates/*.sdf with curated attach-point templates for publication/docking-grade geometry.",
        "sdf_path": str(sdf_path),
        "pdb_path": str(pdb_path),
        "meta_path": str(meta_path),
        "report_path": str(report_path),
    }
    for t in tokens:
        meta["category_counts"][t.kind] = meta["category_counts"].get(t.kind, 0) + 1
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    report_path.write_text(make_report(meta), encoding="utf-8")

    return BuildResult(sequence, tokens, smiles, Chem.MolToMolBlock(mol_export), str(sdf_path), str(pdb_path), str(meta_path), str(report_path), warnings, meta["formula"], meta["exact_mw"], meta["heavy_atoms"], atom_ranges)

def build_batch(items: List[Tuple[str, str]], output_dir: str | Path = ".", optimize: bool = True, num_confs: int = 8) -> List[Dict[str, Any]]:
    """Build many sequences. items = [(name, sequence), ...]. Returns status rows."""
    rows: List[Dict[str, Any]] = []
    for name, sequence in items:
        try:
            result = build_structure(sequence, output_dir=output_dir, name=name, optimize=optimize, num_confs=num_confs)
            rows.append({"name": name, "sequence": sequence, "status": "success", "sdf_path": result.sdf_path, "pdb_path": result.pdb_path, "meta_path": result.meta_path, "report_path": result.report_path, "formula": result.formula, "exact_mw": result.exact_mw, "warnings": " | ".join(result.warnings)})
        except Exception as exc:
            rows.append({"name": name, "sequence": sequence, "status": "failed", "error": str(exc)})
    return rows

def read_batch_csv(path: str | Path) -> List[Tuple[str, str]]:
    p = Path(path)
    with p.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            raise PepforgeBuildError("CSV has no header. Use columns: name,sequence")
        lower = {h.lower(): h for h in reader.fieldnames}
        seq_col = lower.get("sequence") or lower.get("seq")
        name_col = lower.get("name") or lower.get("id") or lower.get("rank")
        if not seq_col:
            raise PepforgeBuildError("CSV must contain a sequence column.")
        out = []
        for i, row in enumerate(reader, start=1):
            seq = (row.get(seq_col) or "").strip()
            if not seq: continue
            name = (row.get(name_col) if name_col else None) or f"pep_{i:03d}"
            name = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(name)).strip("_") or f"pep_{i:03d}"
            out.append((name, seq))
        return out

def describe_parse(sequence: str) -> Dict[str, object]:
    raw = expand_and_tokenize(sequence)
    toks = [classify_token(t) for t in raw]
    try:
        smiles, _, warnings, ranges = tokens_to_smiles(raw)
    except Exception as exc:
        smiles, warnings, ranges = None, [str(exc)], []
    return {
        "version": VERSION,
        "input": sequence,
        "tokens": [{"raw": t.raw, "kind": t.kind, "label": KIND_LABELS.get(t.kind, t.kind), "note": t.note, "parent_residue": t.parent_residue, "modification": t.modification} for t in toks],
        "generated_smiles_preview": smiles,
        "atom_ranges_preview": [asdict(r) for r in ranges],
        "warnings": warnings,
        "aliases_supported": TOKEN_ALIASES,
        "supported_tokens": supported_token_table(),
        "fixed_rule": "Biotin/FITC/Cy5/FAM/TAMRA are labels, not sequence residues; Ahx/PEG/AEEA are linkers; Pal/Myr/Chol are chemical modifications. Side-chain labels use K(FITC)-style syntax.",
    }
