from __future__ import annotations

LOW_SPEC_VALIDATION_BRIDGE_VERSION = "2.1.0"
EXTERNAL_DOCKING_BRIDGE_VERSION = "2.2.0"
EXTERNAL_MD_RESULT_IMPORT_BRIDGE_VERSION = "2.4.0"
PUBLICATION_REPORT_BUILDER_VERSION = "2.5.0"
MD_PREP_BRIDGE_VERSION = "4.0.0"

__all__ = [
    "LOW_SPEC_VALIDATION_BRIDGE_VERSION", "EXTERNAL_DOCKING_BRIDGE_VERSION",
    "EXTERNAL_MD_RESULT_IMPORT_BRIDGE_VERSION", "PUBLICATION_REPORT_BUILDER_VERSION",
    "MD_PREP_BRIDGE_VERSION",
]
