
from __future__ import annotations
import logging
LOGGER = logging.getLogger(__name__)

from pathlib import Path
from typing import Any
import csv
import json
import py_compile
import re

RELEASE_GATE_VERSION = "3.0.0"
TEXT_EXTS = {".md", ".txt", ".py", ".json", ".cff", ".yaml", ".yml", ".ini", ".bat", ".spec", ".iss"}

def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames=None) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = list(rows[0].keys()) if rows else ["check", "status", "detail"]
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow(row)
    return str(path)

def _write_json(path: Path, payload: dict[str, Any]) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)

def _write_text(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return str(path)

def release_gate_check(root_dir: str | Path, output_dir: str | Path) -> dict[str, str]:
    root = Path(root_dir)
    out = Path(output_dir) / "release_gate"
    out.mkdir(parents=True, exist_ok=True)
    rows = []

    def add(check: str, ok: bool, detail: str = ""):
        rows.append({"check": check, "status": "passed" if ok else "failed", "detail": str(detail)})

    version_file = root / "VERSION.txt"
    vf = version_file.read_text(encoding="utf-8", errors="ignore").strip() if version_file.exists() else ""
    add("version_file_3_0_0", vf == RELEASE_GATE_VERSION, vf or "missing")

    citation = root / "CITATION.cff"
    if citation.exists():
        c = citation.read_text(encoding="utf-8", errors="ignore")
        add("citation_schema_1_2_0", 'cff-version: "1.2.0"' in c or "cff-version: 1.2.0" in c, "CITATION.cff")
        add("citation_version_3_0_0", f'version: "{RELEASE_GATE_VERSION}"' in c or f"version: {RELEASE_GATE_VERSION}" in c, "CITATION.cff")
    else:
        add("citation_exists", False, "missing")

    required = [
        "README.md", "README_KO.md", "MANUAL_EN.md", "MANUAL_KO.md",
        "docs/PUBLIC_API_CONTRACT.md", "docs/PUBLIC_OUTPUT_CONTRACT.md",
        "pepforge_cli.py", "peptiforg_core/public_api.py", "peptiforg_core/release_verify_matrix.py",
        "peptiforg_core/release_integrity.py", "peptiforg_core/regression_audit.py", "peptiforg_core/runtime_validation.py",
        "peptiforg_core/source_integrity_audit.py",
    ]
    for rel in required:
        add("required_" + rel, (root / rel).exists(), rel)

    compile_errors = []
    py_count = 0
    for p in sorted(root.rglob("*.py")):
        if "__pycache__" in p.as_posix():
            continue
        py_count += 1
        try:
            py_compile.compile(str(p), doraise=True)
        except Exception as exc:
            compile_errors.append({"file": str(p.relative_to(root)), "error": repr(exc)})
    add("compile_all_python", not compile_errors, f"{py_count} files; {len(compile_errors)} errors")

    try:
        from peptiforg_core.source_integrity_audit import audit_source_tree
        source_audit = audit_source_tree(root)
        add("no_runtime_patch_placeholder_or_duplicate_definitions", source_audit["status"] == "passed", f"{source_audit['finding_count']} findings")
    except Exception as exc:
        add("no_runtime_patch_placeholder_or_duplicate_definitions", False, repr(exc))

    # Direct API smoke checks without recursive CLI subprocess calls.
    try:
        from peptiforg_core.public_api import PUBLIC_API_VERSION
        add("public_api_version", PUBLIC_API_VERSION == RELEASE_GATE_VERSION, PUBLIC_API_VERSION)
    except Exception as exc:
        add("public_api_version", False, repr(exc))

    try:
        from peptiforg_core.experimental_data_importer import make_experimental_template
        template = make_experimental_template(out / "template_smoke")
        add("experimental_template_api", Path(template).exists(), template)
    except Exception as exc:
        add("experimental_template_api", False, repr(exc))

    try:
        from peptiforg_core.workflow_automation_runner import default_workflow_config, save_workflow_config
        cfg = default_workflow_config("GateSmoke")
        cfg_path = save_workflow_config(cfg, out / "workflow_smoke")
        add("workflow_config_api", Path(cfg_path).exists(), cfg_path)
    except Exception as exc:
        add("workflow_config_api", False, repr(exc))

    # Remove bytecode generated by this gate before artifact scanning.
    for cache_name in ["__pycache__", ".pytest_cache", ".mypy_cache"]:
        for cache_dir in list(root.rglob(cache_name)):
            if cache_dir.is_dir():
                import shutil
                shutil.rmtree(cache_dir, ignore_errors=True)
    for generated in list(root.rglob("*.pyc")) + list(root.rglob("*.pyo")):
        try:
            generated.unlink()
        except Exception:
            LOGGER.debug("Optional operation skipped", exc_info=True)
    stale = []
    bad_artifacts = []
    for p in root.rglob("*"):
        rel = p.relative_to(root).as_posix()
        if p.is_file() and p.suffix.lower() in {".pyc", ".pyo", ".exe"}:
            bad_artifacts.append(rel)
        if p.is_dir() and p.name in {"__pycache__", ".pytest_cache", ".mypy_cache", "build", "dist", "outputs"}:
            bad_artifacts.append(rel + "/")
        if p.is_file() and p.suffix.lower() in TEXT_EXTS:
            text = p.read_text(encoding="utf-8", errors="ignore")
            if re.search(r"\\bv8[._-]" + r"7\\b|\\bv8[._-]" + r"8\\b|\\bV8[_-]", text, re.I):
                if rel != "peptiforg_core/full_package_audit.py":
                    stale.append(rel)
            if ("cff-version: " + '"4.0.7"') in text:
                stale.append(rel + " bad-cff-schema")
    add("no_stale_legacy_names", not stale, f"{len(stale)} hits")
    add("no_packaging_artifacts", not bad_artifacts, f"{len(bad_artifacts)} hits")

    passed = sum(1 for r in rows if r["status"] == "passed")
    failed = sum(1 for r in rows if r["status"] == "failed")
    summary = {
        "pepforge_version": RELEASE_GATE_VERSION,
        "passed": passed,
        "failed": failed,
        "python_files_compiled": py_count,
        "compile_errors": compile_errors,
        "stale_hits": stale,
        "bad_artifacts": bad_artifacts,
        "claim_boundary": "Release gate checks software/package readiness only; it is not scientific validation.",
    }

    results_csv = out / "release_gate_results.csv"
    summary_json = out / "release_gate_summary.json"
    report_md = out / "release_gate_report.md"
    _write_csv(results_csv, rows, ["check", "status", "detail"])
    _write_json(summary_json, summary)
    lines = [
        "# Pepforge Release Gate Report",
        "",
        f"Version: {RELEASE_GATE_VERSION}",
        "",
        f"- Passed: {passed}",
        f"- Failed: {failed}",
        f"- Python files compiled: {py_count}",
        "",
        "| Check | Status | Detail |",
        "|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| {r['check']} | {r['status']} | {str(r['detail']).replace('|', '/')} |")
    lines.append("")
    lines.append("Claim boundary: this checks public release readiness, not binding or affinity truth.")
    _write_text(report_md, "\n".join(lines) + "\n")

    return {
        "release_gate_results": str(results_csv),
        "release_gate_summary": str(summary_json),
        "release_gate_report": str(report_md),
    }

__all__ = ["RELEASE_GATE_VERSION", "release_gate_check"]
