
from __future__ import annotations
from pathlib import Path
from typing import Any
import csv, json, hashlib, subprocess, sys

RELEASE_INTEGRITY_VERSION = "4.2.0"

def _sha256(path: Path) -> str:
    h=hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024), b''):
            h.update(chunk)
    return h.hexdigest()

def _write_json(path: Path, payload: dict[str, Any]) -> str:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(payload,indent=2,ensure_ascii=False),encoding='utf-8'); return str(path)

def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames=None) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None: fieldnames=list(rows[0].keys()) if rows else ['check','status','detail']
    with path.open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fieldnames,extrasaction='ignore'); w.writeheader(); [w.writerow(r) for r in rows]
    return str(path)

def _write_text(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text,encoding='utf-8'); return str(path)

def build_file_manifest(root_dir: str|Path) -> list[dict[str, Any]]:
    root=Path(root_dir); rows=[]
    for p in sorted(root.rglob('*')):
        if not p.is_file(): continue
        rel=p.relative_to(root).as_posix()
        if '__pycache__' in rel or rel.endswith('.pyc') or rel.endswith('.pyo'): continue
        rows.append({'relative_path':rel,'size_bytes':p.stat().st_size,'sha256':_sha256(p)})
    return rows

def audit_release_integrity(root_dir: str|Path, output_dir: str|Path, run_nested: bool=False) -> dict[str,str]:
    root=Path(root_dir); out=Path(output_dir)/'release_integrity'; out.mkdir(parents=True,exist_ok=True)
    checks=[]
    def add(n,ok,d=''): checks.append({'check':n,'status':'passed' if ok else 'failed','detail':str(d)})
    rows=build_file_manifest(root); add('file_manifest_created',len(rows)>0,f'{len(rows)} files')
    for rel in ['VERSION.txt','CITATION.cff','README.md','README_KO.md','MANUAL_EN.txt','MANUAL_KO.txt','pepforge_cli.py','peptiforg_core/public_api.py','peptiforg_core/runtime_validation.py','peptiforg_core/full_package_audit.py','peptiforg_core/regression_audit.py','peptiforg_core/release_integrity.py']:
        add('required_'+rel,(root/rel).exists(),rel)
    try:
        import peptiforg_core.public_api as api
        add('public_api_version',getattr(api,'PUBLIC_API_VERSION','')==RELEASE_INTEGRITY_VERSION,getattr(api,'PUBLIC_API_VERSION',''))
    except Exception as exc: add('public_api_version',False,repr(exc))
    try:
        proc=subprocess.run([sys.executable,str(root/'pepforge_cli.py'),'version'],capture_output=True,text=True,timeout=30)
        add('cli_version',proc.returncode==0 and RELEASE_INTEGRITY_VERSION in proc.stdout,proc.stdout.strip() or proc.stderr.strip())
    except Exception as exc: add('cli_version',False,repr(exc))
    if run_nested:
        try:
            proc=subprocess.run([sys.executable,str(root/'pepforge_cli.py'),'validate-runtime','--output-dir',str(out/'runtime')],capture_output=True,text=True,timeout=120)
            add('cli_validate_runtime',proc.returncode==0 and 'runtime_validation_summary' in proc.stdout,proc.stdout[-300:] or proc.stderr[-300:])
        except Exception as exc: add('cli_validate_runtime',False,repr(exc))
        try:
            proc=subprocess.run([sys.executable,str(root/'pepforge_cli.py'),'regression-audit','--root-dir',str(root),'--output-dir',str(out/'regression')],capture_output=True,text=True,timeout=180)
            add('cli_regression_audit',proc.returncode==0 and 'regression_audit_summary' in proc.stdout,proc.stdout[-300:] or proc.stderr[-300:])
        except Exception as exc: add('cli_regression_audit',False,repr(exc))
    # Clean Python caches generated by import/CLI smoke before artifact scanning.
    import shutil
    for cache_name in ['__pycache__', '.pytest_cache', '.mypy_cache']:
        for cache_dir in list(root.rglob(cache_name)):
            if cache_dir.is_dir():
                shutil.rmtree(cache_dir, ignore_errors=True)
    for generated in list(root.rglob('*.pyc')) + list(root.rglob('*.pyo')):
        try:
            generated.unlink()
        except Exception:
            pass

    artifacts=[]
    for p in root.rglob('*'):
        rel=p.relative_to(root).as_posix()
        if p.is_file() and p.suffix.lower() in {'.pyc','.pyo','.exe'}: artifacts.append(rel)
        if p.is_dir() and p.name in {'__pycache__','.pytest_cache','.mypy_cache','build','dist','outputs'}: artifacts.append(rel+'/')
    add('no_packaging_artifacts',len(artifacts)==0,f'{len(artifacts)} hits')
    checks_csv=out/'release_integrity_checks.csv'; manifest_csv=out/'release_file_manifest.csv'; summary_json=out/'release_integrity_summary.json'; report_md=out/'release_integrity_report.md'
    _write_csv(checks_csv,checks,['check','status','detail']); _write_csv(manifest_csv,rows,['relative_path','size_bytes','sha256'])
    passed=sum(1 for r in checks if r['status']=='passed'); failed=sum(1 for r in checks if r['status']=='failed')
    summary={'pepforge_version':RELEASE_INTEGRITY_VERSION,'passed':passed,'failed':failed,'file_count':len(rows),'artifact_hits':artifacts,'claim_boundary':'Release integrity audit checks package integrity and software paths only; it is not scientific validation.'}
    _write_json(summary_json,summary)
    lines=['# Pepforge Release Integrity Report','',f'Version: {RELEASE_INTEGRITY_VERSION}','',f'- Passed: {passed}',f'- Failed: {failed}',f'- Manifest files: {len(rows)}','','| Check | Status | Detail |','|---|---|---|']
    for r in checks: lines.append(f"| {r['check']} | {r['status']} | {str(r['detail']).replace('|','/')} |")
    lines.append(''); lines.append('Claim boundary: this checks release/package integrity, not binding or affinity truth.')
    _write_text(report_md,'\n'.join(lines)+'\n')
    return {'release_integrity_checks':str(checks_csv),'release_file_manifest':str(manifest_csv),'release_integrity_summary':str(summary_json),'release_integrity_report':str(report_md)}

__all__=['RELEASE_INTEGRITY_VERSION','build_file_manifest','audit_release_integrity']
